version: '3'
services:
  postgresql:
    image: postgres
    ports:
      - 5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - /var/lib/postgresql:/var/lib/postgresql
  api:
    image: api
    ports:
      - 80
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
    build:
      context: api
      dockerfile: Dockerfile
    depends_on:
      - postgresql
    links:
      - postgresql
  nginx:
    image: nginx
    ports:
      - 80:80
    build:
      context: nginx
      dockerfile: nginx.dockerfile
    depends_on:
      - api
